language: generic

install:
  - sudo apt install libjudy-dev
  - curl https://ftp.gnu.org/gnu/lightning/lightning-2.1.3.tar.gz | tar -zx
  - cd lightning-2.1.3 && ./configure && make && sudo make install && cd ..
  - make

script:
  - test/test.sh test/
